import os
import pandas as pd
import numpy as np

# path where the events.tsv files generated by both python and matlab scripts are located
valid_dir = r"C:\Users\Laura\Documents\PhD\Soundbrain lab\EAM\data-bids"

python_dir = os.path.join(valid_dir, 'python')
matlab_dir = os.path.join(valid_dir, 'matlab')

sub_dir = [d for d in os.listdir(python_dir) if d.startswith('sub-')]

# write results to text file
f = open("validation_results.txt", "w")
type_mismatch = []
for sub in sub_dir:
    py_dir_sub = os.path.join(python_dir, sub)
    matlab_dir_sub = os.path.join(matlab_dir, sub)
    python_event_files = [f for f in os.listdir(py_dir_sub) if f.endswith('_events.tsv')]
    matlab_event_files = [f for f in os.listdir(matlab_dir_sub) if f.endswith('_events.tsv')]

    if len(python_event_files) != len(matlab_event_files):
        print(f"Number of event files do not match for {sub}. Python: {len(python_event_files)}, Matlab: {len(matlab_event_files)}", file=f)
        if len(python_event_files) < len(matlab_event_files):
            print(f"Missing event files in Python for {sub}: {[f for f in matlab_event_files if f not in python_event_files]}", file=f)
        else:
            print(f"Missing event files in Matlab for {sub}: {[f for f in python_event_files if f not in matlab_event_files]}", file=f)
        continue

    for i, py_file in enumerate(python_event_files):
        py_file_path = os.path.join(py_dir_sub, py_file)
        matlab_file_path = os.path.join(matlab_dir_sub, matlab_event_files[i])
        
        py_events = pd.read_csv(py_file_path, sep='\t')
        matlab_events = pd.read_csv(matlab_file_path, sep='\t')

        print(f"Comparing {py_file} and {matlab_event_files[i]}:", file=f)

        all_close = all(np.isclose(py_events['onset'], matlab_events['onset'], atol=6e-5))
        print(f"All onsets close: {all_close}", file=f)

        if not all_close:
            print("Onsets that do not match:", file=f)
            if all( ~np.isclose(py_events['onset'], matlab_events['onset'], atol=6e-5)):
                print("All onsets are different!", file=f)
            else:
                for idx, (py_onset, matlab_onset) in enumerate(zip(py_events['onset'], matlab_events['onset'])):
                    if not np.isclose(py_onset, matlab_onset, atol=6e-5):
                        print(f"Index {idx}: Python onset = {py_onset}, Matlab onset = {matlab_onset}", file=f)

        types_match = all(py_events['type'] == matlab_events['type'])
        print(f"All types match: {types_match}\n", file=f)
        if not types_match:
            type_mismatch.append(python_event_files)

print("Files with type mismatch:", file=f)
for t in type_mismatch:
    print(t, file=f)
f.close()